/*
Highly divisible triangular number

Problem 12

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

Answer:
	76576500
CPU:
    119614    microseconds 
MEMORY:
    4516    kb
ideone.com
*/
#include <stdio.h>
#include <sys/time.h>
#include <sys/resource.h>

short getDivisors(long tn){//Get number of divisors
        short divisors=1;
    short divisor = 2;
    short preDivisor = divisor;
    short exponent = 1;
    short first = 0;
    while(tn > 1){
        if(!(tn % divisor)){//if divisor
            tn = tn/divisor;
            if(preDivisor != divisor){//if changed the divisor
                divisors *= exponent;//multiplying the exponents
                exponent = 2;//there are two exponents for (exponent+1)
                preDivisor = divisor;//update the new divisor
            }else{//exponent currently +1
                exponent++;   
            }
        }else{//if not divisor
            if(first){//divisor +2; 3 5 7 9 11, aprox numbers primes 
                divisor+=2;
            }else{//2 to 3
                divisor++;
                first= 1;
            }
        }
    }
    divisors *= exponent;
    return divisors;
}

int main(){
    struct timeval t, t2;
    struct rusage use;
    int microseconds;
    gettimeofday(&t, NULL);
    //---------------------------Program v-------------------------------
    long  triangle_number= 0;
    short divisors;
    for(int k= 1; divisors < 500 ; k++){ 
        triangle_number += k;//new number = last number + k
        divisors = getDivisors(triangle_number);//get number divisors
    }
    printf("%ld \n", triangle_number);
	//---------------------------Program ^-------------------------------
	gettimeofday(&t2, NULL);
    microseconds = ((t2.tv_usec - t.tv_usec)  + ((t2.tv_sec - t.tv_sec) * 1000000.0f));
    printf("time code: %d microseconds\n",microseconds);
    getrusage(RUSAGE_SELF, &use);
    printf("Memory: %ld KB\n", (long)use.ru_maxrss);
	return 0;
}

