/*
Even Fibonacci numbers
   
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Answer:
	4613732
CPU:
    34 microseconds
MEMORIA:
	4544 kb
ideone.com
*/
#include <stdio.h>
#include <stdlib.h>
#include <sys/time.h>
#include <sys/resource.h>

int main(){
    struct timeval t, t2;
    struct rusage use;
    int microseconds;
    gettimeofday(&t, NULL);
    //---------------------------Program v-------------------------------
	int sum = 2;
	int n1 = 2, n2 = 1, n = 0;

	while(1){
	    n = n1 + n2; //fn = fn-1 + fn-2
	    if(n > 4000000)// less that four million
            break;
        if (n %2 == 0) //even-valued
            sum += n;
        n2 = n1;
        n1 = n;
	}
	printf("%d \n",sum);
	
	//---------------------------Program ^-------------------------------
	gettimeofday(&t2, NULL);
    microseconds = ((t2.tv_usec - t.tv_usec)  + ((t2.tv_sec - t.tv_sec) * 1000000.0f));
    printf("Time code: %d microseconds\n",microseconds);
    getrusage(RUSAGE_SELF, &use);
    printf("Memory: %ld KB\n", (long)use.ru_maxrss);
	return 0;
}



